config/routes.rb
Ccdu::Application.routes.draw do

  resources :survey_reports do
    get 'accept',:on => :member
    get 'reject',:on => :member
    post 'reason_for_reject' , :on => :member
  end
  
  resources :laboratory_reports do
    get 'district',:on => :collection
    get 'zonal_reports',:on => :collection
    get 'zone_accept', :on => :collection
    get 'zone_reject', :on => :collection
    get 'send_for_testing',:on => :member
    get 'update_testing_report',:on => :member
    post 'submit_update_test',:on => :member
    post 'submit_test',:on => :member
    get 'accept',:on => :member
    get 'reject',:on => :member
    post 'reason_for_reject' , :on => :member
    get 'accepted_sample',:on => :collection
    get 'rejected_sample',:on => :collection
    get 'district_accept', :on => :collection
    get 'district_reject', :on => :collection
  end

  resources :mis_reports do 
    get 'block_mis_report', :on => :collection 
    get 'search_block_mis_report', :on => :collection
    get 'district_mis_report', :on => :collection
    get 'search_district_mis_report', :on => :collection
    get 'zone_mis_report', :on => :collection
    get 'search_zone_mis_report', :on => :collection
    get 'admin_mis_report', :on => :collection
    get 'search_admin_mis_report', :on => :collection
  end
  

  resources :complaints do 
    get 'invoice_submit', :on => :member
    get 'complaint_district', :on => :collection
  end

  resources :priorities
  
  resources :invoices do 
    get 'payment',:on => :collection
    get 'outstanding',:on => :collection
    get 'district_invoice', :on => :collection 
    get 'approve_invoice', :on => :member
    get 'zone_invoice', :on => :collection
    post 'sample_code_count' , :on => :collection
    get 'submit_invoice', :on => :member
    get 'reject_invoice', :on => :member
    post 'remarks_for_rejection', :on => :member
    get 'district_invoice_show', :on => :member
    get 'zone_invoice_show', :on => :member
  end
  

  resources :water_source_types

  resources :mobile_devices do 
    get 'activate_mobile', :on => :member
    get 'deactivate_mobile', :on => :member
    post 'remarks_for_deactivate', :on => :member
  end
  devise_for :users , :controllers => { :sessions => "sessions", :passwords => "passwords"}

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index'
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new'
    end
  end
  match "/users/update_user", :to => "users#update_user"
  match "/admin/users/update_zone", :to => "admin/users#update_zone"
  match "/admin/users/update_district", :to => "admin/users#update_district"
  
  namespace :admin do 
    match '/dashboard' => "dashboard#index", :as => :root
    resources :users 
    resources :habitations
    resources :villages
    resources :grampanchyats
    resources :districts
    resources :zones
    resources :blocks
    resources :sources
  end

  resources :users do
    get 'edit_manager',:on => :member
    post 'update_manager',:on => :member
    get 'accept_user', :on => :member
    get 'reject_user', :on => :member
  end

end

app/models/admin/block.rb
class Admin::Block < ActiveRecord::Base
	belongs_to :district
	belongs_to :user
	has_many :grampanchyats
  attr_accessible :block_name, :district_id, :code, :lab_name, :laboratory_present

  

  before_save :name_code, :labname

  #upcase the block_name, limit code to 3 charactors
  def name_code
  	 
  	self.block_name = self.block_name.upcase
  	
  	self.code = self.block_name[0..2]
  end
  #change laboratory name to nil if laboratory name is nil
  def labname #lab name blank replace with nil else to upcase
    if self.laboratory_present == "No"
      self.lab_name = "NIL"
    else
      if self.lab_name.blank?
         self.lab_name = "NIL"
      else
         self.lab_name = self.lab_name.upcase
      end
    end
  end
end

app/controllers/admin/blocks_controller.rb
class Admin::BlocksController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin'
  # GET /admin/blocks
  # GET /admin/blocks.json
  def index
    @admin_blocks = Admin::Block.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_blocks }
    end
  end

  # GET /admin/blocks/1
  # GET /admin/blocks/1.json
  def show
    @admin_block = Admin::Block.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_block }
    end
  end

  # GET /admin/blocks/new
  # GET /admin/blocks/new.json
  def new
    @admin_block = Admin::Block.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_block }
    end
  end

  # GET /admin/blocks/1/edit
  def edit
    @admin_block = Admin::Block.find(params[:id])
  end

  # POST /admin/blocks
  # POST /admin/blocks.json
  def create
    @admin_block = Admin::Block.new(params[:admin_block])
    #raise params[:toggler].inspect

    if params[:toggler] == "Yes" && @admin_block.lab_name.blank? 
       flash[:notice] = "Please enter laboratory name."
       render :new
    else
      respond_to do |format|
        if @admin_block.save
          format.html { redirect_to admin_blocks_url, notice: 'Block was successfully created.' }
          format.json { render json: @admin_block, status: :created, location: @admin_block }
        else
          format.html { render action: "new" }
          format.json { render json: @admin_block.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /admin/blocks/1
  # PUT /admin/blocks/1.json
  def update
    @admin_block = Admin::Block.find(params[:id])

    respond_to do |format|
      if @admin_block.update_attributes(params[:admin_block])
        format.html { redirect_to admin_blocks_url, notice: 'Block was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/blocks/1
  # DELETE /admin/blocks/1.json
  def destroy
    @admin_block = Admin::Block.find(params[:id])
    @admin_block.destroy

    respond_to do |format|
      format.html { redirect_to admin_blocks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/blocks_helper.rb
module Admin::BlocksHelper
end

app/views/admin/blocks/_form.html.erb
<div class="main">
  <div class="container">
    <div class="row">
      <div class="span12">          
        <div class="widget stacked ">
          <div class="widget-header">
            <i class="icon-pencil"></i>
            <h3>New Block</h3>
          </div> <!-- /widget-header -->
          <div class="widget-content">
            <div style="margin-bottom:10px" class="row-fluid">
              <!-- <div class="span12">
                <a href="<%= admin_blocks_path%>" class="btn">Back</a>          
              </div> -->
            </div>
            <%= form_for  @admin_block, :html => {:id => "block",:class => "form-horizontal"}  do |f| %>
              <% if @admin_block.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@admin_block.errors.count, "error") %> prohibited this from being saved:</h2>
                  <ul>
                    <% @admin_block.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <fieldset>
                <div class="control-group">
                  <label for="name" class="control-label">Block Name</label>
                  <div class="controls">
                    <%= f.text_field :block_name , :class => "input-large"%>
                  </div>
                </div>
                <div class="control-group">
                  <label for="name" class="control-label">Code</label>
                  <div class="controls">
                    <%= f.text_field :code , :class => "input-large"%>
                  </div>
                </div>
                <div class="control-group">
                  <label for="name" class="control-label">Select District</label>
                  <div class="controls">
                    <%= f.collection_select :district_id , Admin::District.all, :id, :district_name ,:prompt => "Select District"%>
                  </div>
                </div>
                <div class="control-group">
                  <label for="name" class="control-label">Is Laboratory Present ?</label>
                  <div class="controls">
                    Yes<%= f.radio_button :laboratory_present, "Yes" %>
                    No <%= f.radio_button :laboratory_present, "No", :checked => true %>
                  </div>
                </div>
                
                <div class="control-group">
                  <label for="name" class="control-label">Laboratory Name</label>
                  <div class="controls">
                    <%= f.text_field :lab_name , :class => "input-large"%>
                    
                  </div>
                </div>
                <div class="control-group">
                  <div class="controls">
                    <%= f.submit "Submit", :class => "btn"%>
                  </div>
                </div>
                
              </fieldset>
            <%end%>
          </div> <!-- /widget-content -->
        </div> <!-- /widget -->
      </div>
    </div> <!-- /row -->
  </div> <!-- /container -->
</div> <!-- /main -->

app/views/admin/blocks/edit.html.erb
<div class="main">
  <div class="container">
    <div class="row">
      <div class="span12">          
        <div class="widget stacked ">
          <div class="widget-header">
            <i class="icon-pencil"></i>
            <h3>Edit Block</h3>
          </div> <!-- /widget-header -->
          <div class="widget-content">
            <div style="margin-bottom:10px" class="row-fluid">
              <!-- <div class="span12">
                <a href="<%= admin_blocks_path%>" class="btn">Back</a>          
              </div> -->
            </div>
            <%= form_for  @admin_block, :html => {:id => "block",:class => "form-horizontal"}  do |f| %>
              <% if @admin_block.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@admin_block.errors.count, "error") %> prohibited this from being saved:</h2>
                  <ul>
                    <% @admin_block.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <fieldset>
                <div class="control-group">
                  <label for="name" class="control-label">Block Name</label>
                  <div class="controls">
                    <%= f.text_field :block_name , :class => "input-large"%>
                  </div>
                </div>
                <div class="control-group">
                  <label for="name" class="control-label">Code</label>
                  <div class="controls">
                    <%= f.text_field :code , :class => "input-large"%>
                  </div>
                </div>
                <div class="control-group">
                  <label for="name" class="control-label">Select District</label>
                  <div class="controls">
                    <%= f.collection_select :district_id , Admin::District.all, :id, :district_name ,:prompt => "Select District"%>
                  </div>
                </div>
                <div class="control-group">
                  <label for="name" class="control-label">Is Laboratory Present ?</label>
                  <div class="controls">
                    Yes<%= f.radio_button :laboratory_present, "Yes" %>
                    No <%= f.radio_button :laboratory_present, "No", :checked => true %>
                  </div>
                </div>
                
                <div class="control-group">
                  <label for="name" class="control-label">Laboratory Name</label>
                  <div class="controls">
                    <%= f.text_field :lab_name , :class => "input-large"%>
                    
                  </div>
                </div>
                <div class="control-group">
                  <div class="controls">
                    <%= f.submit "Submit", :class => "btn"%>
                  </div>
                </div>
                
              </fieldset>
            <%end%>
          </div> <!-- /widget-content -->
        </div> <!-- /widget -->
      </div>
    </div> <!-- /row -->
  </div> <!-- /container -->
</div> <!-- /main -->

app/views/admin/blocks/index.html.erb
<div class="main">

  <div class="container">

      <div class="row">
        
        <div class="span12">          
          
          <div class="widget stacked ">
            
            <div class="widget-header">
              <i class="icon-pencil"></i>
              <h3>All Blocks</h3>
            </div> <!-- /widget-header -->
        
              <div class="widget-content">
              
                <div class="row-fluid">
                  <div class="span12">
                  
                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
              
                      <tr>
                        <td>&nbsp;</td>
                        <td>
                          <%#= link_to "Back", admin_root_path, :class => "btn"%>
                          <%= link_to "New Block", new_admin_block_path, :class=>"btn", :type=>"reset"%>
                        </td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                    </table>
                  </div>
                </div>
                </br>
                <section id="tables">
                  
                    <table class="table table-bordered table-striped">
                      
                              <thead>
                                <tr>
                                  <th>Sr. No. </th>
                                  <th>Block name</th>
                                  <th>Code</th>
                                  <th>Is Laboratory Present ?</th>
                                  <th>Laboratory Name</th>
                                  <th>District</th>
                                  <% if current_user.has_role? :admin %>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                  <% end %>
                                </tr>
                              </thead>
                            <% @admin_blocks.each_with_index.each do |admin_block,i |  %> 
                              <tbody>
                                <tr>
                                  <td><%= i+1 %></td>
                                  <td><%= admin_block.block_name rescue nil%></td>
                                  <td><%= admin_block.code rescue nil%></td>
                                  <td><%= admin_block.laboratory_present rescue nil%></td>
                                  <td><%= admin_block.lab_name rescue nil%></td>
                                  <td><%= admin_block.district.district_name rescue nil%></td>
                                  <% if current_user.has_role? :admin %>
                                    <td><%= link_to "Edit", edit_admin_block_path(admin_block),:class => "btn" %></td>
                                    <td><%= link_to "Delete", admin_block, method: :delete, data: { confirm: 'Are you sure?' } ,:class => "btn"%></td>
                                  <% end %>
                                </tr>
                              </tbody>
                      <% end %> 
                    </table>
                         
                          
                         
                  <!-- <section id="paginations">
                    
                    
                    <div class="pagination">
                      <ul>
                        <li><a href="javascript:;">Prev</a></li>
                        <li class="active">
                          <a href="javascript:;">1</a>
                        </li>
                        <li><a href="javascript:;">2</a></li>
                        <li><a href="javascript:;">3</a></li>
                        <li><a href="javascript:;">4</a></li>
                        <li><a href="javascript:;">Next</a></li>
                      </ul>
                    </div>
                            
                  </section> -->
                </section>
              </div> <!-- /widget-content -->
          </div> <!-- /widget -->
        </div>
      </div> <!-- /row -->
  </div> <!-- /container -->
</div> <!-- /main -->
    