config/routes.rb
Ccdu::Application.routes.draw do

  resources :survey_reports do
    get 'accept',:on => :member
    get 'reject',:on => :member
    post 'reason_for_reject' , :on => :member
  end
  
  resources :laboratory_reports do
    get 'district',:on => :collection
    get 'zonal_reports',:on => :collection
    get 'zone_accept', :on => :collection
    get 'zone_reject', :on => :collection
    get 'send_for_testing',:on => :member
    get 'update_testing_report',:on => :member
    post 'submit_update_test',:on => :member
    post 'submit_test',:on => :member
    get 'accept',:on => :member
    get 'reject',:on => :member
    post 'reason_for_reject' , :on => :member
    get 'accepted_sample',:on => :collection
    get 'rejected_sample',:on => :collection
    get 'district_accept', :on => :collection
    get 'district_reject', :on => :collection
  end

  resources :mis_reports do 
    get 'block_mis_report', :on => :collection 
    get 'search_block_mis_report', :on => :collection
    get 'district_mis_report', :on => :collection
    get 'search_district_mis_report', :on => :collection
    get 'zone_mis_report', :on => :collection
    get 'search_zone_mis_report', :on => :collection
    get 'admin_mis_report', :on => :collection
    get 'search_admin_mis_report', :on => :collection
  end
  

  resources :complaints do 
    get 'invoice_submit', :on => :member
    get 'complaint_district', :on => :collection
  end

  resources :priorities
  
  resources :invoices do 
    get 'payment',:on => :collection
    get 'outstanding',:on => :collection
    get 'district_invoice', :on => :collection 
    get 'approve_invoice', :on => :member
    get 'zone_invoice', :on => :collection
    post 'sample_code_count' , :on => :collection
    get 'submit_invoice', :on => :member
    get 'reject_invoice', :on => :member
    post 'remarks_for_rejection', :on => :member
    get 'district_invoice_show', :on => :member
    get 'zone_invoice_show', :on => :member
  end
  

  resources :water_source_types

  resources :mobile_devices do 
    get 'activate_mobile', :on => :member
    get 'deactivate_mobile', :on => :member
    post 'remarks_for_deactivate', :on => :member
  end
  devise_for :users , :controllers => { :sessions => "sessions", :passwords => "passwords"}

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index'
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new'
    end
  end
  match "/users/update_user", :to => "users#update_user"
  match "/admin/users/update_zone", :to => "admin/users#update_zone"
  match "/admin/users/update_district", :to => "admin/users#update_district"
  
  namespace :admin do 
    match '/dashboard' => "dashboard#index", :as => :root
    resources :users 
    resources :habitations
    resources :villages
    resources :grampanchyats
    resources :districts
    resources :zones
    resources :blocks
    resources :sources
  end

  resources :users do
    get 'edit_manager',:on => :member
    post 'update_manager',:on => :member
    get 'accept_user', :on => :member
    get 'reject_user', :on => :member
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

      user ||= User.new # guest user (not logged in)

      entities = [User, MobileDevice, MobileUser, BlockLaboratory]
      
      if user.has_role? :admin
        can :manage, :all
      elsif user.has_role? :block
        can :manage, entities
       
      end
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/block_laboratory.rb
class BlockLaboratory < ActiveRecord::Base
  attr_accessible :address, :labname, :user_id

  belongs_to :user

  validates_presence_of :labname, :user_id
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
  attr_accessible :action_taken, :assigned_on, :assigned_to, :block_name, :closed_by, :closed_on, :district_name, :incident_description, :incident_title, :other_impact, :raised_by, :raised_on, :sample_impacted, :status, :supplier_name,:user_id,:priority
  belongs_to :user 
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  attr_accessible :amount,:user_id, :block_name, :district_name, :invoice_date, :invoice_no, :is_invoice, :no_of_sample, :remark,:zone_name,:remarks_for_rejection, :is_dist_invoice,:is_invoiced, :invoice_id
  
  validates_presence_of :invoice_date, :invoice_no, :no_of_sample, :remark, :amount
  belongs_to :user

  validates :invoice_no, :presence   => true ,:uniqueness => true
end

app/models/mobile_device.rb
class MobileDevice < ActiveRecord::Base
  attr_accessible :imei, :manufacturer_name, :phone_no, :purchase_date,:user_id,:remarks_for_deactivate, :status

  validates_presence_of :imei, :manufacturer_name, :phone_no, :purchase_date,:user_id

end

app/models/mobile_user.rb
class MobileUser < ActiveRecord::Base
  attr_accessible :imei, :mobile_user_id,:user_id

  belongs_to :user

  validates_presence_of :imei, :mobile_user_id,:user_id
end

app/models/parameter.rb
class Parameter < ActiveRecord::Base
  attr_accessible :alkalinity, :bact, :chloride, :fluroide, :hardness, 
  :nitrate, :no_of_chemical_sample, :ph, :residual_chlorine, :sanitary_survey, :tds
end

app/models/priority.rb
class Priority < ActiveRecord::Base
  attr_accessible :priority_name
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  attr_accessible :name, :display_name
  scopify
end

app/models/survey_report.rb
class SurveyReport < ActiveRecord::Base


  attr_accessible :date_time,:districtname,:user_id, :grampanchayat,:latitude,:longitude, :habitation, :source_code, :source_location, :source_name, :surveyor_name, :village, :water_source_type, :image, :image1, :ph, :tds, :residual_chlorine, :fluoride, :chloride, :nitrate, :alkaliniy, :total_hardness, :bacteriological, :actions, :is_tested, :reason_for_rejecting, :district_name, :block_name,:survey_no,:remarks,:water_source_code, :reason_for_dist_rejected, :is_dist_approved,:postmonsoon, :district_level_status,:zone_name
  belongs_to :user

  has_attached_file :image, 
  					        :styles => { :small => "150x150>" },
  					        :storage => :s3,
					          :s3_credentials => "#{Rails.root}/config/s3.yml",
					          :path => "image/:id/:style/:basename.:extension"

  has_attached_file :image1, 
  					        :styles => { :small => "150x150>" },
  					        :storage => :s3,
					          :s3_credentials => "#{Rails.root}/config/s3.yml",
					          :path => "image1/:id/:style/:basename.:extension"

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username ,:role_ids, :mobile_no,
  :user_fullname, :zone_name, :district_name, :block_name,:status,:block_manager_id,:is_transfer, :old_manager_id
  # attr_accessible :title, :body
  has_many :zones
  has_many :district
  has_many :blocks
  has_many :grampanchyats
  has_many :villages
  has_many :habitations
  has_many :mobile_devices
  has_many :mobile_users
  has_many :block_laboratories
  has_many :survey_reports
  has_many :invoices
  has_many :complaints
  validates :username, :presence   => true ,:uniqueness => true
  
end

app/models/water_source_type.rb
class WaterSourceType < ActiveRecord::Base
  attr_accessible :source_type
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/parameters_helper.rb
module ParametersHelper
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_app_menu.html.erb
<div class="subnavbar">

	<div class="subnavbar-inner">
	
		<div class="container">
			
			<a class="btn-subnavbar collapsed" data-toggle="collapse" data-target=".subnav-collapse">
				<i class="icon-reorder"></i>
			</a>

			<div class="subnav-collapse collapse">
				<ul class="mainnav">
				  <% if current_user.has_role? :district %>
				        
    					<li class="dropdown">
						  <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"> Laboratory Report<b class="caret"></b></a>
						
						    <ul class="dropdown-menu">
							    <li class="dropdown">	<a href="<%= district_laboratory_reports_path %>" ><span>Tested Report</span></a></li>
		                        <li class="divider"></li>
		                        <li class="dropdown">	<a href="<%= district_accept_laboratory_reports_path%>" ><span>Accepted Report</span></a></li>
		                        <li class="divider"></li>
		                        <li class="dropdown">	<a href="<%= district_reject_laboratory_reports_path%>" ><span>Rejected Report</span></a></li>
					 	    </ul>
					    </li>

    					<li class="dropdown">
    						<a href="<%= district_invoice_invoices_path %>">

    							<span>Invoices</span>
    						</a>	    				
    					</li>

    					<li class="dropdown">
    						<a href="<%= district_mis_report_mis_reports_path %>">

    							<span>Summary Report</span>
    						</a>	    				
    					</li>
    					
    					<li class="dropdown">
    						<a href="<%= complaint_district_complaints_path %>">

    							<span>Complaint Box</span>
    						</a>	    				
    					</li>
				    <% elsif current_user.has_role? :block %>
					<li class="dropdown">
						<a href="<%= users_path%>">
							
							<span>Users</span>
						</a>	    				
					</li>
					

					<li class="dropdown">					
						<a href="<%= survey_reports_path%>">
							
							<span>Surveyor Report</span>
						</a>	
					</li>
					
					<li class="dropdown">
					  <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"> Laboratory Report<b class="caret"></b></a>
					
					    <ul class="dropdown-menu">
						    <li class="dropdown">	<a href="<%= laboratory_reports_path %>" ><span>Testing Report</span></a></li>
	                        <li class="divider"></li>
	                        <li class="dropdown">	<a href="<%= accepted_sample_laboratory_reports_path%>" ><span>Accept Report</span></a></li>
	                        <li class="divider"></li>
	                        <li class="dropdown">	<a href="<%= rejected_sample_laboratory_reports_path%>" ><span>Reject Report</span></a></li>
				 	    </ul>
					</li>
					
					<li class="dropdown">
					  <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"> Invoice<b class="caret"></b></a>
					
					  <ul class="dropdown-menu">
					    <li class="dropdown">	<a href="<%= invoices_path %>" ><span>Generate Invoice</span></a></li>
		              <li class="divider"></li>
		              <li class="dropdown">	<a href="<%= payment_invoices_path %>" ><span>Payment Received</span></a></li>
		              <li class="divider"></li>
		              <li class="dropdown">	<a href="<%= outstanding_invoices_path %>" ><span>Outstanding Payment</span></a></li>
				 		</ul>
					</li>

					<li class="dropdown">					
						<a href="<%= block_mis_report_mis_reports_path%>">
							
							<span>Summary Report</span>
						</a>	
				    </li>

				    <li class="dropdown">					
						<a href="<%= complaints_path%>">
							
							<span>Complaint Box</span>
						</a>	
				    </li>


					<%else current_user.has_role? :zone%>
                        <li class="dropdown">
						  <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"> Laboratory Report<b class="caret"></b></a>
						
						    <ul class="dropdown-menu">
		                        <li class="divider"></li>
		                        <li class="dropdown">	<a href="<%= zone_accept_laboratory_reports_path%>" ><span>Accepted Report</span></a></li>
		                        <li class="divider"></li>
		                        <li class="dropdown">	<a href="<%= zone_reject_laboratory_reports_path%>" ><span>Rejected Report</span></a></li>
					 	    </ul>
					    </li>

    					<li class="dropdown">
    						<a href="<%= zone_invoice_invoices_path %>">

    							<span>Invoices</span>
    						</a>	    				
    					</li>
    					<li class="dropdown">
    						<a href="<%= zone_mis_report_mis_reports_path %>">

    							<span>Summary Report</span>
    						</a>	    				
    					</li>

    					
              
					<%end%>
				</ul>
			</div> <!-- /.subnav-collapse -->

		</div> <!-- /container -->
	
	</div> <!-- /subnavbar-inner -->

</div> <!-- /subnavbar -->
    

app/views/shared/_footer.html.erb
<div class="footer">
		
	<div class="container">
		
		<div class="row">
			
			<div id="footer-copyright" class="span6">
				&copy; CCDU ltd.
			</div> <!-- /span6 -->
			
			 
			
		</div> <!-- /row -->
		
	</div> <!-- /container -->
	
</div> <!-- /footer -->

app/views/shared/_menu.html.erb
<div class="subnavbar">

	<div class="subnavbar-inner">
	
		<div class="container">
			
			<a class="btn-subnavbar collapsed" data-toggle="collapse" data-target=".subnav-collapse">
				<i class="icon-reorder"></i>
			</a>

			<div class="subnav-collapse collapse">
				<% if current_user.has_role? :admin %>
					<ul class="mainnav">
					
						

					    <li class="dropdown">
							
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								
								Manage Water Source
								<b class="caret"></b>
							</a>
							
							<ul class="dropdown-menu">
								<!-- <li><a href="#">My Profile</a></li> -->
								
								
						
							    
                                <li class="divider"></li>
						 		<li class="dropdown">					
									<a href="<%= admin_zones_path%>" >
										
										<span>Zones</span>
										
									</a>	    
					
						 		</li>
                                <li class="divider"></li>
						 		<li class="dropdown">					
									<a href="<%= admin_districts_path%>" >
										
										<span>Districts</span>
										
									</a>	    
					
						 		</li>
                                <li class="divider"></li>
						 		<li class="dropdown">					
									<a href="<%= admin_blocks_path%>">
										
										<span>Blocks</span>
									</a>	
					            </li>
                               <li class="divider"></li>
					           <li class="dropdown">					
									<a href="<%= admin_grampanchyats_path%>">
										
										<span>Grampanchyats</span>
									</a>	
					           </li> 
                               <li class="divider"></li>
					           <li class="dropdown">					
									<a href="<%= admin_villages_path%>">
										
										<span>Villages</span>
									</a>	
					           </li>
					
					           <li class="divider"></li>
								<li class="dropdown">					
									<a href="<%= admin_habitations_path%>">
										
										<span>Habitations</span>
									</a>	
							   </li>
					            <li class="divider"></li>
								<li class="dropdown">					
									<a href="<%= admin_sources_path%>">
										
										<span>Add Water Source</span>
									</a>	
								</li>
								<!-- <li class="divider"></li>
								<li class="dropdown">					
									<a href="<%= water_source_types_path%>">
										
										<span>Add Water Source Type</span>
									</a>	
								</li>
								<li class="divider"></li>
								<li class="dropdown">					
									<a href="<%= priorities_path%>">
										
										<span>Add Priority</span>
									</a>	
								</li> -->
                               
								
							</ul>
						</li>

						<li class="dropdown">
							<a href="<%= admin_users_path%>">
								
								<span>Users</span>
							</a>	    				
						</li>

						<li class="dropdown">					
							<a href="<%= mobile_devices_path%>" >
								
								<span>Mobile Devices</span>
							</a>	    
					
						</li>

						<li class="dropdown">
    						<a href="<%= admin_mis_report_mis_reports_path %>">

    							<span>Summary Report</span>
    						</a>	    				
    					</li>
				    </ul>
				<%end%>
			</div> <!-- /.subnav-collapse -->

		</div> <!-- /container -->
	
	</div> <!-- /subnavbar-inner -->

</div> <!-- /subnavbar -->
    