config/routes.rb
Ccdu::Application.routes.draw do

  resources :survey_reports do
    get 'accept',:on => :member
    get 'reject',:on => :member
    post 'reason_for_reject' , :on => :member
  end
  
  resources :laboratory_reports do
    get 'district',:on => :collection
    get 'zonal_reports',:on => :collection
    get 'zone_accept', :on => :collection
    get 'zone_reject', :on => :collection
    get 'send_for_testing',:on => :member
    get 'update_testing_report',:on => :member
    post 'submit_update_test',:on => :member
    post 'submit_test',:on => :member
    get 'accept',:on => :member
    get 'reject',:on => :member
    post 'reason_for_reject' , :on => :member
    get 'accepted_sample',:on => :collection
    get 'rejected_sample',:on => :collection
    get 'district_accept', :on => :collection
    get 'district_reject', :on => :collection
  end

  resources :mis_reports do 
    get 'block_mis_report', :on => :collection 
    get 'search_block_mis_report', :on => :collection
    get 'district_mis_report', :on => :collection
    get 'search_district_mis_report', :on => :collection
    get 'zone_mis_report', :on => :collection
    get 'search_zone_mis_report', :on => :collection
    get 'admin_mis_report', :on => :collection
    get 'search_admin_mis_report', :on => :collection
  end
  

  resources :complaints do 
    get 'invoice_submit', :on => :member
    get 'complaint_district', :on => :collection
  end

  resources :priorities
  
  resources :invoices do 
    get 'payment',:on => :collection
    get 'outstanding',:on => :collection
    get 'district_invoice', :on => :collection 
    get 'approve_invoice', :on => :member
    get 'zone_invoice', :on => :collection
    post 'sample_code_count' , :on => :collection
    get 'submit_invoice', :on => :member
    get 'reject_invoice', :on => :member
    post 'remarks_for_rejection', :on => :member
    get 'district_invoice_show', :on => :member
    get 'zone_invoice_show', :on => :member
  end
  

  resources :water_source_types

  resources :mobile_devices do 
    get 'activate_mobile', :on => :member
    get 'deactivate_mobile', :on => :member
    post 'remarks_for_deactivate', :on => :member
  end
  devise_for :users , :controllers => { :sessions => "sessions", :passwords => "passwords"}

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index'
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new'
    end
  end
  match "/users/update_user", :to => "users#update_user"
  match "/admin/users/update_zone", :to => "admin/users#update_zone"
  match "/admin/users/update_district", :to => "admin/users#update_district"
  
  namespace :admin do 
    match '/dashboard' => "dashboard#index", :as => :root
    resources :users 
    resources :habitations
    resources :villages
    resources :grampanchyats
    resources :districts
    resources :zones
    resources :blocks
    resources :sources
  end

  resources :users do
    get 'edit_manager',:on => :member
    post 'update_manager',:on => :member
    get 'accept_user', :on => :member
    get 'reject_user', :on => :member
  end

end

app/controllers/laboratory_reports_controller.rb
class LaboratoryReportsController < ApplicationController
  before_filter :authenticate_user!, :except => [:create]
  skip_before_filter :verify_authenticity_token, :only => [:new, :create]
  respond_to :html, :js, :json
  require 'will_paginate/array'
  
  def index
    #raise params.inspect
    
    #raise (start_from != nil || start_to != nil).inspect
      if params[:subaction] == "update"
        start_from = params[:start_date] rescue ""
        start_to   = params[:end_date] rescue ""
        source_name = params[:source_name][:source_name_eq] rescue ""
        water_source_type = params[:water_source_type][:water_source_type_eq] rescue ""
        habitation = params[:habitation][:habitation_eq] rescue ""
        
        if start_from > start_to 
         flash[:notice] = "Start date cannot be greater than end date"
         @survey_reports = current_user.survey_reports.find(:all, :conditions=>"actions = 1", :order=>"id desc").paginate(page: params[:page], per_page: 10) 
        elsif start_from <= start_to

          if start_from.blank?
            @survey_reports = current_user.survey_reports.where("source_name = ? or water_source_type = ? or habitation = ?", source_name,water_source_type,habitation).find(:all,:conditions=>"actions = 1", :order=>"id desc").paginate(page: params[:page], per_page: 10)
          else
            @survey_reports = current_user.survey_reports.where("created_at >= ? and Date(created_at) <= ?", start_from,start_to).find(:all,:conditions=>"actions = 1", :order=>"id desc").paginate(page: params[:page], per_page: 10)
          end
        else
          @survey_reports = current_user.survey_reports.where("created_at >= ? and Date(created_at) <= ? and source_name = ? and water_source_type = ? and habitation = ?",start_from,start_to, source_name,water_source_type,habitation).find(:all,:conditions=>"actions = 1", :order=>"id desc").paginate(page: params[:page], per_page: 10) 
        end
      else

        @survey_reports = current_user.survey_reports.find(:all, :conditions=>"actions = 1", :order=>"id desc").paginate(page: params[:page], per_page: 10)
      end
      

    
    respond_to do |format|
      format.html # index.html.erb
      format.xls
      format.pdf do
         render :pdf => "survey_reports"
      end
    end
  end
  
  def show
    @survey_report = SurveyReport.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @survey_report }
    end
  end

 
  
  def send_for_testing
    @survey_report = SurveyReport.find(params[:id])
  end
  
  def submit_test
    @survey_report = SurveyReport.find(params[:id])
    if @survey_report.update_attributes(params[:survey_report])
      #respond_with(@survey_report, location: survey_reports_path)
    else
      render 'send_for_testing'
    end
  end
  
  def accept
    @survey_report = SurveyReport.find(params[:id])
    @survey_report.is_dist_approved = 1
    @survey_report.save!
    respond_with(@survey_report, location: survey_reports_path)
  end
  
  def reject
    @survey_report = SurveyReport.find(params[:id])
  end

  def district

    if params[:subaction] == "update"
        start_from = params[:start_date] rescue ""
        start_to   = params[:end_date] rescue ""
        block_name = params[:block_name][:block_name_eq] rescue ""
        
        if start_from > start_to 
         flash[:notice] = "Start date cannot be greater than end date"

         @survey_reports = SurveyReport.where('districtname = ?', current_user.district_name).find(:all, :conditions=>"is_tested = 1 and is_dist_approved=0", :order=>"id desc").paginate(page: params[:page], per_page: 10)
         block
        else start_from <= start_to

          if start_from.blank?
            @user = User.find_by_block_name(block_name)
            @survey_reports = SurveyReport.where('user_id = ?',@user ).find(:all, :conditions=>"is_tested = 1 and is_dist_approved=0", :order=>"id desc").paginate(page: params[:page], per_page: 10)
            block #refer block method
          else
            @survey_reports = SurveyReport.where("created_at >= ? and Date(created_at) <= ? and districtname = ?", start_from,start_to,current_user.district_name).find(:all, :conditions=>"is_tested = 1 and is_dist_approved=0", :order=>"id desc").paginate(page: params[:page], per_page: 10)
            block
          end
        end
      else

        @survey_reports = SurveyReport.where('districtname = ?', current_user.district_name).find(:all, :conditions=>"is_tested = 1 and is_dist_approved=0", :order=>"id desc").paginate(page: params[:page], per_page: 10)
        block #refer block method
        
      end

      respond_to do |format|
        format.html # index.html.erb
        format.xls
        format.pdf do
           render :pdf => "survey_reports"
        end
      end
  end

  def district_accept
      #raise current_user.district_name.inspect
      if params[:subaction] == "update"
        start_from = params[:start_date] rescue ""
        start_to   = params[:end_date] rescue ""
        block_name = params[:block_name][:block_name_eq] rescue ""
        
        if start_from > start_to 
         flash[:notice] = "Start date cannot be greater than end date"

         @survey_reports = SurveyReport.where('districtname = ?', current_user.district_name).find(:all,
                                              :select => 'id,water_source_code,ph,tds,residual_chlorine,fluoride,chloride,nitrate,alkaliniy,total_hardness,bacteriological,reason_for_rejecting,postmonsoon', 
                                              :conditions=>"is_tested = 1 and is_dist_approved=1", 
                                              :order=>"id desc").paginate(page: params[:page], per_page: 10)
         block #refer block method
        else start_from <= start_to

          if start_from.blank?
            @user = User.where('block_name = ?', block_name)
            @survey_reports = SurveyReport.where('user_id = ?',@user).find(:all,
                                                 :select => 'id,water_source_code,ph,tds,residual_chlorine,fluoride,chloride,nitrate,alkaliniy,total_hardness,bacteriological,reason_for_rejecting,postmonsoon',
                                                 :conditions=>"is_tested = 1 and is_dist_approved=1", 
                                                 :order=>"id desc").paginate(page: params[:page], per_page: 10)
            block
          else
            @survey_reports = SurveyReport.where("created_at >= ? and Date(created_at) <= ?, districtname = ?", start_from,start_to,current_user.district_name).find(:all,
                                                :select => 'id,water_source_code,ph,tds,residual_chlorine,fluoride,chloride,nitrate,alkaliniy,total_hardness,bacteriological,reason_for_rejecting,postmonsoon',
                                                :conditions=>"is_tested = 1 and is_dist_approved=1",
                                                :order=>"id desc").paginate(page: params[:page], per_page: 10)
            block
          end
        end
      else

        @survey_reports = SurveyReport.where('districtname = ?',current_user.district_name).find(:all,
                                            :select => 'id,water_source_code,ph,tds,residual_chlorine,fluoride,chloride,nitrate,alkaliniy,total_hardness,bacteriological,reason_for_rejecting,postmonsoon',
                                            :conditions=>"is_tested = 1 and is_dist_approved=1",
                                            :order=>"id desc").paginate(page: params[:page], per_page: 10)
        block
      end

    respond_to do |format|
      format.html # index.html.erb
      format.xls
      format.pdf do
         render :pdf => "survey_reports"
      end
    end
  end

  

  def district_reject
    
    if params[:subaction] == "update"
        start_from = params[:start_date] rescue ""
        start_to   = params[:end_date] rescue ""
        block_name = params[:block_name][:block_name_eq] rescue ""
        
        if start_from > start_to 
         flash[:notice] = "Start date cannot be greater than end date"

         @survey_reports = SurveyReport.where('districtname',current_user.district_name).find(:all,
                                             :select => 'id,water_source_code,ph,tds,residual_chlorine,fluoride,chloride,nitrate,alkaliniy,total_hardness,bacteriological,reason_for_rejecting,postmonsoon',
                                             :conditions=>"is_tested = 1 and is_dist_approved=2",
                                             :order=>"id desc").paginate(page: params[:page], per_page: 10)
         block
        else start_from <= start_to

          if start_from.blank?
            @user = User.find_by_block_name(block_name)
            @survey_reports = SurveyReport.where('user_id = ?',@user).find(:all,
                                          :select => 'id,water_source_code,ph,tds,residual_chlorine,fluoride,chloride,nitrate,alkaliniy,total_hardness,bacteriological,reason_for_rejecting,postmonsoon',
                                          :conditions=>"is_tested = 1 and is_dist_approved=2",
                                          :order=>"id desc").paginate(page: params[:page], per_page: 10)
            #@survey_reports = @survey_report.find_all_by_districtname(current_user.district_name, :conditions=>"is_tested = 1 and is_dist_approved=1", :order=>"id desc").paginate(page: params[:page], per_page: 10)
            block
          else
            @survey_reports = SurveyReport.where("created_at >= ? and Date(created_at) <= ? and districtname = ?", start_from,start_to,current_user.district_name).find(:all ,
                                          :select => 'id,water_source_code,ph,tds,residual_chlorine,fluoride,chloride,nitrate,alkaliniy,total_hardness,bacteriological,reason_for_rejecting,postmonsoon',

app/helpers/laboratory_reports_helper.rb
module LaboratoryReportsHelper
end

app/views/laboratory_reports/accepted_sample.html.erb
<%= stylesheet_link_tag "facebox.css" %>

<%= javascript_include_tag "facebox.js", "jquery.validate.min" %>
<script>
(function() {

  jQuery(function() {
  jQuery('#start_date').datepicker( 
    { altField  : '#start_date',  // selector of the hidden input field you want sent to the server
      dateFormat: 'yy-mm-dd',
      altFormat : 'yy-mm-dd' } );
    });


}).call(this);

</script>

<script>
(function() {

  jQuery(function() {
  jQuery('#end_date').datepicker( 
    { altField  : '#end_date',  // selector of the hidden input field you want sent to the server
      dateFormat: 'yy-mm-dd',
      altFormat : 'yy-mm-dd' } );
    });


}).call(this);

</script> 
<div class="main">
  <div class="container">
    <div class="row">
      <div class="span12">          
        <div class="widget stacked ">
          <div class="widget-header">
            <i class="icon-pencil"></i>
            <h3>Accepted at District Lab </h3>
          </div> <!-- /widget-header -->
          <div class="widget-content">
            <div class="row-fluid">
              <div class="span12">
                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                  <%= form_tag accepted_sample_laboratory_reports_path ,:method => :get do %>
                  <tr>
                    <td>From Date </td>
                    <td><span class="controls">
                      <%= text_field_tag :start_date,Date.today %>
                    </span></td>
                    <td>To Date </td>
                    <td><span class="controls">
                      <%= text_field_tag :end_date,Date.today %>
                       </span>
                    </td>
            
                  </tr>
                  
                  <tr>
                    <td>&nbsp;</td>
                    <td>
                      <%= button_tag  :submit , name: "subaction",value: "update", :class => "btn btn btn-primary" %>
                      <!-- <button class="btn btn btn-primary" type="reset">Show</button> -->
                      <%= link_to "Clear", accepted_sample_laboratory_reports_path, :class=>"btn btn btn-primary"%>
                      
                    </td>
                      <td>&nbsp;</td>
                      <td>&nbsp;</td>
                      <td>&nbsp;</td>
                      <td>&nbsp;</td>
                  </tr>
                 <% end %>
                </table>
              </div>
            </div>
            </br>
            <section id="tables">
              <div class="row-fluid">
                <div class="span6">
                  <h3>LABORATORY REPORT</h3>
                </div>
                <div class="span6" style="text-align:right">
                  <%= link_to image_tag('/assets/excel.png', :border=>"0", :align=>"absmiddle") + " Excel", accepted_sample_laboratory_reports_path(params.merge(format: "xls")), :method=> :get, :class=>"btn btn-secondary" %>
                  <%= link_to image_tag('/assets/pdf.png', :border=>"0", :align=>"absmiddle") + " PDF", accepted_sample_laboratory_reports_path(params.merge(format: "pdf")), :method=> :get, :class=>"btn btn-secondary" %>
                   
                </div>
              </div>
              
              <table class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Sr. No. </th>
                    <th>Sample Code</th>
                    <th>pH</th>
                    <th>TDS</th>
                    <th>Residual Chlorine</th>
                    <th>Fluoride</th>
                    <th>Chloride</th>
                    <th>Nitrate</th>
                    <th>Alkalinity</th>
                    <th>Total Hardness</th>
                    <th>Pre Monsoon</th>
                    <th>Post Monsoon</th>
                    <!-- th style="width:20%">Action</th> -->
                  </tr>
                </thead>
                 <tbody>
                <% @survey_reports.each_with_index.each do |survey_report,i |  %> 
                 
                    <tr id="<%= dom_id(survey_report) %>">
                      <td><%= i+1 %></td>
                      <td><%= survey_report.water_source_code rescue nil%></td>
                      <td><%= survey_report.ph rescue nil%></td>
                      <td><%= survey_report.tds rescue nil%></td>
                      <td><%= survey_report.residual_chlorine rescue nil%></td>
                      <td><%= survey_report.fluoride rescue nil%></td>
                      <td><%= survey_report.chloride rescue nil%></td>
                      <td><%= survey_report.nitrate rescue nil%></td>
                      <td><%= survey_report.alkaliniy rescue nil%></td>
                      <td><%= survey_report.total_hardness rescue nil%></td>
                      <td><%= survey_report.bacteriological rescue nil %></td>
                      <td><%= survey_report.postmonsoon rescue nil %></td>
                      <!-- <td><div style="float:left; margin-right:3px;"><%= link_to "View", laboratory_report_path(survey_report), :class=>"btn" %> </div></td> -->
                    </tr>
                <% end %> 
                </tbody>
              </table>
              <section id="paginations">
                <div class="digg_pagination">
                  <%= will_paginate @survey_reports %>
                </div>
              </section>
            </section>
          </div> <!-- /widget-content -->
        </div> <!-- /widget -->
      </div>
    </div> <!-- /row -->
  </div> <!-- /container -->
</div> <!-- /main -->
    

app/views/laboratory_reports/district_reject.html.erb
<%= stylesheet_link_tag "facebox.css" %>

<%= javascript_include_tag "facebox.js", "jquery.validate.min" %>
<script>
(function() {

  jQuery(function() {
  jQuery('#start_date').datepicker( 
    { altField  : '#start_date',  // selector of the hidden input field you want sent to the server
      dateFormat: 'yy-mm-dd',
      altFormat : 'yy-mm-dd' } );
    });


}).call(this);

</script>

<script>
(function() {

  jQuery(function() {
  jQuery('#end_date').datepicker( 
    { altField  : '#end_date',  // selector of the hidden input field you want sent to the server
      dateFormat: 'yy-mm-dd',
      altFormat : 'yy-mm-dd' } );
    });


}).call(this);

</script>
<div class="main">
  <div class="container">
    <div class="row">
      <div class="span12">          
        <div class="widget stacked ">
          <div class="widget-header">
            <i class="icon-pencil"></i>
            <h3>Rejected by District Lab</h3>
          </div> <!-- /widget-header -->
          <div class="widget-content">
            <div class="row-fluid">
              <div class="span12">
                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                  <%= form_tag district_reject_laboratory_reports_path ,:method => :get do %>
                  <tr>
                    <td>From Date </td>
                    <td><span class="controls">
                      <%= text_field_tag :start_date,Date.today %>
                    </span></td>
                    <td>To Date </td>
                    <td><span class="controls">
                      <%= text_field_tag :end_date ,Date.today%>
                       </span>
                    </td>

                    <td>Block </td>
                    <td><span class="controls">
                      <%= collection_select :block_name, :block_name_eq, @blocks, :block_name, :block_name ,{:prompt => "Select Block Name"}%>
                      </span>
                    </td>
                  </tr>
                  <tr>
                    <td>&nbsp;</td>
                    <td>
                      <%= button_tag  :submit , name: "subaction",value: "update", :class => "btn btn btn-primary" %>
                      <!-- <button class="btn btn btn-primary" type="reset">Show</button> -->
                      <%= link_to "Clear", district_reject_laboratory_reports_path, :class=>"btn btn btn-primary"%>
                      
                    </td>
                      <td>&nbsp;</td>
                      <td>&nbsp;</td>
                      <td>&nbsp;</td>
                      <td>&nbsp;</td>
                  </tr>
                 <% end %>
                </table>
              </div>
            </div>
            </br>
            <section id="tables">
              <div class="row-fluid">
                <div class="span6">
                  <h3>LABORATORY REPORT</h3>
                </div>
                <div class="span6" style="text-align:right">
                  <%= link_to image_tag('/assets/excel.png', :border=>"0", :align=>"absmiddle") + " Excel", district_reject_laboratory_reports_path(params.merge(format: "xls")), :method=> :get, :class=>"btn btn-secondary" %>
                  <%= link_to image_tag('/assets/pdf.png', :border=>"0", :align=>"absmiddle") + " PDF", district_reject_laboratory_reports_path(params.merge(format: "pdf")), :method=> :get, :class=>"btn btn-secondary" %>
                   
                </div>
              </div>
              
              <table class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Sr. No. </th>
                    <th>Sample Code</th>
                    <th>pH</th>
                    <th>TDS</th>
                    <th>Residual Chlorine</th>
                    <th>Fluoride</th>
                    <th>Chloride</th>
                    <th>Nitrate</th>
                    <th>Alkalinity</th>
                    <th>Total Hardness</th>
                    <th>Pre Monsoon</th>
                    <th>Post Monsoon</th>
                    <th>Reason For Rejecting</th>
                    
                  </tr>
                </thead>
                 <tbody>
                <% @survey_reports.each_with_index.each do |survey_report,i |  %> 
                 
                    <tr id="<%= dom_id(survey_report) %>">
                      <td><%= i+1 %></td>
                      <td><%= survey_report.water_source_code rescue nil%></td>
                      <td><%= survey_report.ph rescue nil%></td>
                      <td><%= survey_report.tds rescue nil%></td>
                      <td><%= survey_report.residual_chlorine rescue nil%></td>
                      <td><%= survey_report.fluoride rescue nil%></td>
                      <td><%= survey_report.chloride rescue nil%></td>
                      <td><%= survey_report.nitrate rescue nil%></td>
                      <td><%= survey_report.alkaliniy rescue nil%></td>
                      <td><%= survey_report.total_hardness rescue nil%></td>
                      <td><%= survey_report.bacteriological rescue nil %></td>
                      <td><%= survey_report.postmonsoon rescue nil %></td>
                      <td><%= survey_report.reason_for_dist_rejected rescue nil%></td>
                      
                    </tr>
                <% end %> 
                </tbody>
              </table>
              <section id="paginations">
                <div class="digg_pagination">
                  <%#= will_paginate @survey_reports %>
                </div>
              </section>
            </section>
          </div> <!-- /widget-content -->
        </div> <!-- /widget -->
      </div>
    </div> <!-- /row -->
  </div> <!-- /container -->
</div> <!-- /main -->
    

app/views/laboratory_reports/index.xls.erb
<div class="page-header-custom">
            <h3 align = "center">
               Laboratory Reports</h3>
            <!--subnav-->
          
        </div>

  <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">  
    <tr>
      <th>Sr. No. </th>
      <th>Source name</th>
      <th>Source code</th>
      <th>Source location</th>
      <th>Habitation</th>
      <th>Village</th>
      <th>Grampanchayat</th>
      <th>Water source type</th>
      <th>Date time</th>
      <th>Surveyor name</th>
    </tr>

    <% @survey_reports.each_with_index.each do |survey_report,i |  %> 
      <tbody>
        <tr>
          <td><%= i+1 %></td>
          <td><%= survey_report.source_name rescue nil%></td>
          <td><%= survey_report.source_code rescue nil%></td>
          <td><%= survey_report.source_location rescue nil%></td>
          <td><%= survey_report.habitation rescue nil%></td>
          <td><%= survey_report.village rescue nil%></td>
          <td><%= survey_report.grampanchayat rescue nil%></td>
          <td><%= survey_report.water_source_type rescue nil%></td>
          <td><%= survey_report.created_at.strftime("%d-%m-%Y %I:%M %p") rescue nil%></td>
          <td><%= survey_report.surveyor_name rescue nil%></td>
        </tr>
      </tbody>
    <% end %> 
    

app/views/laboratory_reports/rejected_sample.html.erb
<%= stylesheet_link_tag "facebox.css" %>

<%= javascript_include_tag "facebox.js", "jquery.validate.min" %>
<script>
(function() {

  jQuery(function() {
  jQuery('#start_date').datepicker( 
    { altField  : '#start_date',  // selector of the hidden input field you want sent to the server
      dateFormat: 'yy-mm-dd',
      altFormat : 'yy-mm-dd' } );
    });


}).call(this);

</script>

<script>
(function() {

  jQuery(function() {
  jQuery('#end_date').datepicker( 
    { altField  : '#end_date',  // selector of the hidden input field you want sent to the server
      dateFormat: 'yy-mm-dd',
      altFormat : 'yy-mm-dd' } );
    });


}).call(this);

</script>
<div class="main">
  <div class="container">
    <div class="row">
      <div class="span12">          
        <div class="widget stacked ">
          <div class="widget-header">
            <i class="icon-pencil"></i>
            <h3>Rejected by District Lab</h3>
          </div> <!-- /widget-header -->
          <div class="widget-content">
            <div class="row-fluid">
              <div class="span12">
                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                  <%= form_tag rejected_sample_laboratory_reports_path ,:method => :get do %>
                  <tr>
                    <td>From Date </td>
                    <td><span class="controls">
                      <%= text_field_tag :start_date,Date.today %>
                    </span></td>
                    <td>To Date </td>
                    <td><span class="controls">
                      <%= text_field_tag :end_date ,Date.today%>
                       </span>
                    </td>
                  </tr>
                  <tr>
                    <td>&nbsp;</td>
                    <td>
                      <%= button_tag  :submit , name: "subaction",value: "update", :class => "btn btn btn-primary" %>
                      <!-- <button class="btn btn btn-primary" type="reset">Show</button> -->
                      <%= link_to "Clear", rejected_sample_laboratory_reports_path, :class=>"btn btn btn-primary"%>
                      
                    </td>
                      <td>&nbsp;</td>
                      <td>&nbsp;</td>
                      <td>&nbsp;</td>
                      <td>&nbsp;</td>
                  </tr>
                 <% end %>
                </table>
              </div>
            </div>
            </br>
            <section id="tables">
              <div class="row-fluid">
                <div class="span6">
                  <h3>LABORATORY REPORT</h3>
                </div>
                <div class="span6" style="text-align:right">
                  <%= link_to image_tag('/assets/excel.png', :border=>"0", :align=>"absmiddle") + " Excel", rejected_sample_laboratory_reports_path(params.merge(format: "xls")), :method=> :get, :class=>"btn btn-secondary" %>
                  <%= link_to image_tag('/assets/pdf.png', :border=>"0", :align=>"absmiddle") + " PDF", rejected_sample_laboratory_reports_path(params.merge(format: "pdf")), :method=> :get, :class=>"btn btn-secondary" %>
                   
                </div>
              </div>
              
              <table class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Sr. No. </th>
                    <th>Sample Code</th>
                    <th>pH</th>
                    <th>TDS</th>
                    <th>Residual Chlorine</th>
                    <th>Fluoride</th>
                    <th>Chloride</th>
                    <th>Nitrate</th>
                    <th>Alkalinity</th>
                    <th>Total Hardness</th>
                    <th>Pre Monsoon</th>
                    <th>Post Monsoon</th>
                    <th>Reason For Reject</th>
                    <th>Action</th>
                  </tr>
                </thead>
                 <tbody>
                <% @survey_reports.each_with_index.each do |survey_report,i |  %> 
                 
                    <tr id="<%= dom_id(survey_report) %>">
                      <td><%= i+1 %></td>
                      <td><%= survey_report.water_source_code rescue nil%></td>
                      <td><%= survey_report.ph rescue nil%></td>
                      <td><%= survey_report.tds rescue nil%></td>
                      <td><%= survey_report.residual_chlorine rescue nil%></td>
                      <td><%= survey_report.fluoride rescue nil%></td>
                      <td><%= survey_report.chloride rescue nil%></td>
                      <td><%= survey_report.nitrate rescue nil%></td>
                      <td><%= survey_report.alkaliniy rescue nil%></td>
                      <td><%= survey_report.total_hardness rescue nil%></td>
                      <td><%= survey_report.bacteriological rescue nil %></td>
                      <td><%= survey_report.postmonsoon rescue nil %></td>
                      <td><%= survey_report.reason_for_dist_rejected rescue nil%></td>
                      <td><div style="float:left; margin-right:3px;"><%= link_to "Retest Report", update_testing_report_laboratory_report_path(survey_report), remote: true, :class=>"btn" %> </div></td>
                    </tr>
                <% end %> 
                </tbody>
              </table>
              <section id="paginations">
                <div class="digg_pagination">
                  <%= will_paginate @survey_reports %>
                </div>
              </section>
            </section>
          </div> <!-- /widget-content -->
        </div> <!-- /widget -->
      </div>
    </div> <!-- /row -->
  </div> <!-- /container -->
</div> <!-- /main -->
    