config/routes.rb
Ccdu::Application.routes.draw do

  resources :survey_reports do
    get 'accept',:on => :member
    get 'reject',:on => :member
    post 'reason_for_reject' , :on => :member
  end
  
  resources :laboratory_reports do
    get 'district',:on => :collection
    get 'zonal_reports',:on => :collection
    get 'zone_accept', :on => :collection
    get 'zone_reject', :on => :collection
    get 'send_for_testing',:on => :member
    get 'update_testing_report',:on => :member
    post 'submit_update_test',:on => :member
    post 'submit_test',:on => :member
    get 'accept',:on => :member
    get 'reject',:on => :member
    post 'reason_for_reject' , :on => :member
    get 'accepted_sample',:on => :collection
    get 'rejected_sample',:on => :collection
    get 'district_accept', :on => :collection
    get 'district_reject', :on => :collection
  end

  resources :mis_reports do 
    get 'block_mis_report', :on => :collection 
    get 'search_block_mis_report', :on => :collection
    get 'district_mis_report', :on => :collection
    get 'search_district_mis_report', :on => :collection
    get 'zone_mis_report', :on => :collection
    get 'search_zone_mis_report', :on => :collection
    get 'admin_mis_report', :on => :collection
    get 'search_admin_mis_report', :on => :collection
  end
  

  resources :complaints do 
    get 'invoice_submit', :on => :member
    get 'complaint_district', :on => :collection
  end

  resources :priorities
  
  resources :invoices do 
    get 'payment',:on => :collection
    get 'outstanding',:on => :collection
    get 'district_invoice', :on => :collection 
    get 'approve_invoice', :on => :member
    get 'zone_invoice', :on => :collection
    post 'sample_code_count' , :on => :collection
    get 'submit_invoice', :on => :member
    get 'reject_invoice', :on => :member
    post 'remarks_for_rejection', :on => :member
    get 'district_invoice_show', :on => :member
    get 'zone_invoice_show', :on => :member
  end
  

  resources :water_source_types

  resources :mobile_devices do 
    get 'activate_mobile', :on => :member
    get 'deactivate_mobile', :on => :member
    post 'remarks_for_deactivate', :on => :member
  end
  devise_for :users , :controllers => { :sessions => "sessions", :passwords => "passwords"}

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index'
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new'
    end
  end
  match "/users/update_user", :to => "users#update_user"
  match "/admin/users/update_zone", :to => "admin/users#update_zone"
  match "/admin/users/update_district", :to => "admin/users#update_district"
  
  namespace :admin do 
    match '/dashboard' => "dashboard#index", :as => :root
    resources :users 
    resources :habitations
    resources :villages
    resources :grampanchyats
    resources :districts
    resources :zones
    resources :blocks
    resources :sources
  end

  resources :users do
    get 'edit_manager',:on => :member
    post 'update_manager',:on => :member
    get 'accept_user', :on => :member
    get 'reject_user', :on => :member
  end

end

app/models/admin/source.rb
class Admin::Source < ActiveRecord::Base
  attr_accessible :source_name, :code

  validates_presence_of :source_name, :code

  before_save :upname

  #upcase the source name
  def upname
  	self.source_name = self.source_name.upcase
  end
end

app/controllers/admin/sources_controller.rb
class Admin::SourcesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  layout 'admin'
  # GET /admin/sources
  # GET /admin/sources.json
  def index
    @admin_sources = Admin::Source.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_sources }
    end
  end

  # GET /admin/sources/1
  # GET /admin/sources/1.json
  def show
    @admin_source = Admin::Source.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_source }
    end
  end

  # GET /admin/sources/new
  # GET /admin/sources/new.json
  def new
    @admin_source = Admin::Source.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_source }
    end
  end

  # GET /admin/sources/1/edit
  def edit
    @admin_source = Admin::Source.find(params[:id])
  end

  # POST /admin/sources
  # POST /admin/sources.json
  def create
    @admin_source = Admin::Source.new(params[:admin_source])

    respond_to do |format|
      if @admin_source.save
        format.html { redirect_to admin_sources_url, notice: 'Source was successfully created.' }
        format.json { render json: admin_sources_url, status: :created, location: @admin_source }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/sources/1
  # PUT /admin/sources/1.json
  def update
    @admin_source = Admin::Source.find(params[:id])

    respond_to do |format|
      if @admin_source.update_attributes(params[:admin_source])
        format.html { redirect_to admin_sources_url, notice: 'Source was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/sources/1
  # DELETE /admin/sources/1.json
  def destroy
    @admin_source = Admin::Source.find(params[:id])
    @admin_source.destroy

    respond_to do |format|
      format.html { redirect_to admin_sources_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/sources_helper.rb
module Admin::SourcesHelper
end

app/views/admin/sources/_form.html.erb
<div class="main">
  <div class="container">
    <div class="row">
      <div class="span12">          
        <div class="widget stacked ">
          <div class="widget-header">
            <i class="icon-pencil"></i>
            <h3>New Water Source</h3>
          </div> <!-- /widget-header -->
          <div class="widget-content">
            <div style="margin-bottom:10px" class="row-fluid">
              <!-- <div class="span12">
                <a href="<%= admin_sources_path%>" class="btn">Back</a>          
              </div> -->
            </div>
            <%= form_for @admin_source, :html => {:id => "source",:class => "form-horizontal"} do |f| %>
              <% if @admin_source.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@admin_source.errors.count, "error") %> prohibited this admin_source from being saved:</h2>
                  <ul>
                    <% @admin_source.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <fieldset>
                <div class="control-group">
                  <label for="name" class="control-label">Source Name</label>
                  <div class="controls">
                    <%= f.text_field :source_name , :class => "input-large"%>
                  </div>
                </div>
                <div class="control-group">
                  <label for="name" class="control-label">Source Code</label>
                  <div class="controls">
                    <%= f.text_field :code , :class => "input-large"%>
                  </div>
                </div>
                <div class="control-group">
                  <div class="controls">
                    <%= f.submit "Submit", :class => "btn"%>
                  </div>
                </div>
              </fieldset>
            <%end%>
          </div> <!-- /widget-content -->
        </div> <!-- /widget -->
      </div>
    </div> <!-- /row -->
  </div> <!-- /container -->
</div> <!-- /main -->

app/views/admin/sources/edit.html.erb
<div class="main">
  <div class="container">
    <div class="row">
      <div class="span12">          
        <div class="widget stacked ">
          <div class="widget-header">
              <i class="icon-pencil"></i>
              <h3>Edit Water Source</h3>
          </div> <!-- /widget-header -->
          <div class="widget-content">
            <div style="margin-bottom:10px" class="row-fluid">
              <!-- <div class="span12">
                <a href="<%= admin_sources_path%>" class="btn">Back</a>          
              </div> -->
            </div>
            <%= form_for @admin_source, :html => {:id => "source",:class => "form-horizontal"} do |f| %>
              <% if @admin_source.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@admin_source.errors.count, "error") %> prohibited this admin_source from being saved:</h2>
                  <ul>
                    <% @admin_source.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <fieldset>
                <div class="control-group">
                  <label for="name" class="control-label">Source Name</label>
                  <div class="controls">
                    <%= f.text_field :source_name , :class => "input-large"%>
                  </div>
                </div>
                <div class="control-group">
                  <label for="name" class="control-label">Source Code</label>
                  <div class="controls">
                    <%= f.text_field :code , :class => "input-large"%>
                  </div>
                </div>
                <div class="control-group">
                  <div class="controls">
                    <%= f.submit "Submit", :class => "btn"%>
                  </div>
                </div>
              </fieldset>
            <%end%>
          </div> <!-- /widget-content -->
        </div> <!-- /widget -->
      </div>
    </div> <!-- /row -->
  </div> <!-- /container -->
</div> <!-- /main -->

app/views/admin/sources/index.html.erb
<div class="main">

  <div class="container">

      <div class="row">
        
        <div class="span12">          
          
          <div class="widget stacked ">
            
            <div class="widget-header">
              <i class="icon-pencil"></i>
              <h3>All Water Sources</h3>
            </div> <!-- /widget-header -->
        
              <div class="widget-content">
              
                <div class="row-fluid">
                  <div class="span12">
                  
                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
              
                      <tr>
                        <td>&nbsp;</td>
                        <td>
                          <%#= link_to "Back", admin_root_path, :class => "btn"%>
                          <%= link_to "New Source", new_admin_source_path, :class=>"btn", :type=>"reset"%>
                        </td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                    </table>
                  </div>
                </div>
                </br>
                <section id="tables">
                  
                    <table class="table table-bordered table-striped">
                      
                              <thead>
                                <tr>
                                  <th>Sr. No. </th>
                                  <th>Source name</th>
                                  <th>Code</th>
                                  <% if current_user.has_role? :admin %>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                  <% end %>
                                </tr>
                              </thead>
                            <% @admin_sources.each_with_index.each do |admin_source,i |  %> 
                              <tbody>
                                <tr>
                                  <td><%= i+1 %></td>
                                  <td><%= admin_source.source_name rescue nil%></td>
                                  <td><%= admin_source.code rescue nil%></td>
                                  <% if current_user.has_role? :admin %>
                                    <td><%= link_to "Edit", edit_admin_source_path(admin_source) ,:class => "btn"%></td>
                                    <td><%= link_to "Delete", admin_source, method: :delete, data: { confirm: 'Are you sure?' },:class => "btn" %></td>
                                  <% end %>
                                </tr>
                              </tbody>
                      <% end %> 
                    </table>
                         
                          
                         
                  <!-- <section id="paginations">
                    
                    
                    <div class="pagination">
                      <ul>
                        <li><a href="javascript:;">Prev</a></li>
                        <li class="active">
                          <a href="javascript:;">1</a>
                        </li>
                        <li><a href="javascript:;">2</a></li>
                        <li><a href="javascript:;">3</a></li>
                        <li><a href="javascript:;">4</a></li>
                        <li><a href="javascript:;">Next</a></li>
                      </ul>
                    </div>
                            
                  </section> -->
                </section>
              </div> <!-- /widget-content -->
          </div> <!-- /widget -->
        </div>
      </div> <!-- /row -->
  </div> <!-- /container -->
</div> <!-- /main -->
    

app/views/admin/sources/show.html.erb
<div class="main">

    <div class="container">

      <div class="row">
      	
		<div class="span12">      		
      		
      		<div class="widget stacked ">
      			
      			<div class="widget-header">
      				<i class="icon-pencil"></i>
      				<h3>Show Water Source</h3>
  				</div> <!-- /widget-header -->
				<div class="widget-content">

					<div class="row-fluid">
                  <div class="span12">
                  
                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
              
                      <tr>
                        <td>&nbsp;</td>
                        <td>
                          <%= link_to "Back", admin_sources_path, :class => "btn"%>
                          <%= link_to "Edit Water Source", edit_admin_source_path(@admin_source), :class=>"btn", :type=>"reset"%>
                        </td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                    </table>
                  </div>
                </div>
                </br>
				
				
				<section id="tables">
					
					
					
					
					
				  <table class="table table-bordered table-striped">
						       
						        <tbody>
						          <tr>
						            <td>Source name</td>
						            <td><%= @admin_source.source_name rescue nil%></td>
						            
					              </tr>
					              
								 </tbody>
			      </table>
						      
						      
						     

						
						
						      
				  </section>
					      
						
					
					
					
				</div> <!-- /widget-content -->
					
			</div> <!-- /widget -->
      		
	    </div>
      	
      </div> <!-- /row -->

    </div> <!-- /container -->
    
</div> <!-- /main -->